Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 3, in <module>
    i in range (2,lim)
NameError: name 'i' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 1, in <module>
    a = int (input ("enter a number : "))
ValueError: invalid literal for int() with base 10: ''
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 3, in <module>
    i in range (2,lim)
NameError: name 'i' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 3, in <module>
    for i in range (2,lim):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
it prime bro
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
it prime bro
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12
it aint prime
it aint prime
it aint prime
it aint prime
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12
it aint prime
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12
it aint prime
>>> 
=============================== RESTART: Shell ===============================
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
it prime bro
it prime bro
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
>>> 
>>> 
>>> 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
>>> 
>>> 
>>> 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12'
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 1, in <module>
    a = int (input ("enter a number : "))
ValueError: invalid literal for int() with base 10: "12'"
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 12
it aint prime
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 7
3
>>> 6
6
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 6
it aint prime
2
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 4
it aint prime
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 3
prime
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 3
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 9, in <module>
    if i==lim and is_prime:
NameError: name 'i' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 3
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 9, in <module>
    prime (i)
NameError: name 'prime' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 3
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 9, in <module>
    print (i)
NameError: name 'i' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
enter a number : 3
is prime
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
*
*
*
*
*
*
*
*
*
*
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
* * * * * * * * * * 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================

* 
* * 
* * * 
* * * * 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================

* 
* * 
* * * 
* * * * 
* * * * * 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================

* 2 1 
* 3 1 * 3 2 
* 4 1 * 4 2 * 4 3 
* 5 1 * 5 2 * 5 3 * 5 4 
* 6 1 * 6 2 * 6 3 * 6 4 * 6 5 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================

* 2 1 
* 3 1 * 3 2 
* 4 1 * 4 2 * 4 3 
* 5 1 * 5 2 * 5 3 * 5 4 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
1
* 2
* * 3
* * * 4
* * * * 5
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
1
2
3
4
5
1
* 2
* * 3
* * * 4
* * * * 5
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
* * * * * * * * * * * * * * * * * * * * * 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
it aint prime
it aint prime
prime
it aint prime
prime
it aint prime
it aint prime
it aint prime
prime
it aint prime
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
prime:  17
prime:  19
prime:  23
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 3, in <module>
    print (ch, "-", end=' ')
NameError: name 'ch' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
a - r - z - o - o - o - o - o - 
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
a - r - z - o - o - o - o - o - o
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
Traceback (most recent call last):
  File "C:\Users\Arzoo\Desktop\PYTHON\A.py", line 3, in <module>
    for a in rang (5):
NameError: name 'rang' is not defined
>>> 
================ RESTART: C:\Users\Arzoo\Desktop\PYTHON\A.py ================
*
**
***
****
*****
>>> 
